apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: pegasus-travel-planner
build:
  artifacts:
    - image: pegasus-travel-planner
      context: .
      docker:
        dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
      - k8s/deps/*
      - k8s/spring-boot-app.yaml
portForward:
  - resourceType: service
    resourceName: postgres-service
    port: 5432
    localPort: 5432
profiles:
  - name: depsOnly
    build:
      artifacts: []
    deploy:
      kubectl:
        manifests:
          - k8s/deps/*
