datasource:
  host: localhost
  username: user
  password: password
  schema: public
  database: db

logging:
  level:
    org:
      springframework:
        web: DEBUG
        security: DEBUG

      pegasus:
        backendapi: INFO
