context:
  initializer:
    classes: org.pegasus.backendapi.AppInitializer

spring:
  datasource:
    url: jdbc:postgresql://${datasource.host}/${datasource.database}?currentSchema=${datasource.schema}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: ${datasource.schema}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    parameters:
      schema: ${datasource.schema}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

api:
  yandex:
    travel:
      url: "https://whitelabel.travel.yandex-net.ru"
      oAuthToken: "y0_AgAAAAAE1cObAAhpCwAAAAEFibDGAABlMyI06xpIU4DEAD3GK6OwBufW_w"
