context:
  initializer:
    classes: org.pegasus.backendapi.AppInitializer

spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/db
    username: user
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
