context:
  initializer:
    classes: org.pegasus.backendapi.AppInitializer

spring:
  datasource:
    url: jdbc:postgresql://${datasource.host}/${datasource.database}?currentSchema=${datasource.schema}
    username: ${datasource.username}
    password: ${datasource.password}
    driver-class-name: org.postgresql.Driver

  liquibase:
    default-schema: ${datasource.schema}
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    parameters:
      schema: ${datasource.schema}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate

  rsocket:
    server:
      port: 7000
      transport: websocket

security:
  salt: 'my-32-char-secret-key-which-is-secure'
