apiVersion: apps/v1
kind: Deployment
metadata:
  name: pegasus-backend-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pegasus-backend-api
  template:
    metadata:
      labels:
        app: pegasus-backend-api
    spec:
      containers:
        - name: spring-boot-example
          image: skaffold-pegasus-backend-api
          ports:
            - containerPort: 8080
